import Head from "next/head";
import React, { Fragment } from "react";
import { useRouter } from "next/router";

import Search from "@app/search/Search";
import { getAllTags, getAllPosts } from "@lib/postsUtil";

export default function TagsPage(props) {
  const router = useRouter();

  const query = router.query.s?.toLowerCase();
  return (
    <Fragment>
      <Head>
        <title>Nuntium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search {...props} query={query} />
    </Fragment>
  );
}

export const getStaticProps = async () => {
  const tags = getAllTags();
  const posts = getAllPosts();
  return {
    props: { posts },
  };
};
