import Head from "next/head";
import { Fragment } from "react";

import Home from "../app/home/Home";

export default function MyHome() {
  return (
    <Fragment>
      <Head>
        <title>Nuntium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </Fragment>
  );
}
