import Head from "next/head";
import { Fragment } from "react";

import Home from "../app/home/Home";
import { getAllPosts, getFeaturedPost, getHerodPost } from "../lib/posts-util";

export default function MyHome(props) {
  return (
    <Fragment>
      <Head>
        <title>Nuntium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home {...props} />
    </Fragment>
  );
}

export const getStaticProps = async () => {
  const posts = getAllPosts();
  const heroPost = getHerodPost();
  const featuredPost = getFeaturedPost();

  return {
    props: {
      heroPost,
      featuredPost,
    },
  };
};
