import Head from "next/head";
import { Fragment } from "react";
import EditorPick from "../components/EditorPick/EditorPick";
import Hero from "../components/Hero/Hero";
import FeaturedArticle from "../components/FeaturedArticle/FeaturedArticle";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Nuntium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <EditorPick />
      <FeaturedArticle />
    </Fragment>
  );
}
