import Head from "next/head";
import { Fragment } from "react";
import LoginForm from "../components/LoginForm/LoginForm";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Nuntium Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginForm />
    </Fragment>
  );
}
