import Head from "next/head";
import { Fragment } from "react";

import Tags from "@app/tags/Tags";
import { getAllTags } from "@lib/posts-util";

export default function MyHome({ tags }) {
  return (
    <Fragment>
      <Head>
        <title>Nuntium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tags tags={tags} />
    </Fragment>
  );
}

export const getStaticProps = async () => {
  const tags = getAllTags();
  return {
    props: { tags },
  };
};
